// Auth Actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

// User Actions
export const USER_LOADED = 'USER_LOADED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

// Request Actions
export const GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS';
export const EDIT_REQUEST_SUCCESS = 'EDIT_REQUEST_SUCCESS';
export const LIKE_REQUEST = 'LIKE_REQUEST';
export const UNLIKE_REQUEST = 'UNLIKE_REQUEST';
export const POST_REQUEST_COMMENT = 'POST_REQUEST_COMMENT';
export const DELETE_REQUEST_COMMENT = 'DELETE_REQUEST_COMMENT';
export const EDIT_REQUEST_COMMENT = 'EDIT_REQUEST_COMMENT';
export const REQUEST_ERROR = 'REQUEST_ERROR';

// Poll Actions
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const GET_POLL_SUCCESS = 'GET_POLL_SUCCESS';
export const GET_POLL_ERROR = 'GET_POLL_ERROR';
